# Generated by Django 2.2.7 on 2019-12-07 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_subscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Subscriber', 'verbose_name_plural': 'Subscribers'},
        ),
    ]
